# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy application code
COPY . .

# Build TypeScript project
RUN npm run build

# Default command to start the MCP server
CMD ["node", "dist/index.js"]
